import React from 'react';
import { Link } from 'react-router-dom';

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="legal-inner">
        <Link to="/" className="legal-back">← Back</Link>
        <h1>Terms of Service</h1>
        <p className="legal-date">Last updated: March 2026</p>

        <h2>Acceptance</h2>
        <p>By creating an account or using Headwater you agree to these terms. If you do not agree, do not use the service.</p>

        <h2>What Headwater does</h2>
        <p>Headwater generates AI-powered summaries of YouTube videos and delivers them via a daily email digest. Summaries are produced by the Anthropic Claude API and may be incomplete or inaccurate. They are intended as a time-saving aid, not a substitute for watching the original video.</p>

        <h2>Acceptable use</h2>
        <p>You may use Headwater for personal, non-commercial purposes. You may not:</p>
        <ul>
          <li>Use the service to scrape, bulk-download, or redistribute summaries at scale</li>
          <li>Attempt to reverse-engineer or circumvent any rate limits or access controls</li>
          <li>Use the service in any way that violates applicable law</li>
        </ul>

        <h2>AI-generated content</h2>
        <p>All summaries are generated by an AI model and may contain errors, omissions, or misrepresentations of the source material. Headwater makes no warranty as to the accuracy of any summary. Always refer to the original video for authoritative information.</p>

        <h2>Intellectual property</h2>
        <p>Summaries are derived from third-party video content. Headwater does not claim ownership of the underlying video content. Short excerpts and quotes are included for commentary and informational purposes.</p>

        <h2>Account termination</h2>
        <p>You may delete your account at any time. We reserve the right to suspend or terminate accounts that violate these terms.</p>

        <h2>Disclaimer of warranties</h2>
        <p>The service is provided "as is" without warranties of any kind. We do not guarantee uptime, accuracy of summaries, or uninterrupted delivery of digest emails.</p>

        <h2>Limitation of liability</h2>
        <p>To the fullest extent permitted by law, Headwater's liability for any claim arising from use of the service is limited to the amount you paid us in the 12 months preceding the claim.</p>

        <h2>Changes</h2>
        <p>We may update these terms. Continued use of the service after changes constitutes acceptance.</p>

        <h2>Contact</h2>
        <p>Questions? Email <a href="mailto:hello@headwater.app">hello@headwater.app</a>.</p>
      </div>
    </div>
  );
}
